// <auto-generated />
using Hotel_API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Hotel_API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20220105102331_Add-Hotel-Room-Amenity-Tables")]
    partial class AddHotelRoomAmenityTables
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.13")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Hotel_API.Models.Amenity", b =>
                {
                    b.Property<int>("AmenityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AmenityName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("AmenityId");

                    b.ToTable("Amenities");

                    b.HasData(
                        new
                        {
                            AmenityId = 1,
                            AmenityName = "Computer and Internet access"
                        },
                        new
                        {
                            AmenityId = 2,
                            AmenityName = "Washer and Dryer"
                        },
                        new
                        {
                            AmenityId = 3,
                            AmenityName = "Towels"
                        });
                });

            modelBuilder.Entity("Hotel_API.Models.Hotel", b =>
                {
                    b.Property<int>("HotelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("HotelName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("StreetAddress")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("HotelId");

                    b.ToTable("Hotels");

                    b.HasData(
                        new
                        {
                            HotelId = 1,
                            City = "Marrakech",
                            Country = "Moroco",
                            HotelName = "La Mamounia",
                            PhoneNumber = "XXXXX-XXX-XXXXXX",
                            State = "Marrakech state",
                            StreetAddress = "Moroco street"
                        },
                        new
                        {
                            HotelId = 2,
                            City = "Amman",
                            Country = "Jordan",
                            HotelName = "Al Harir Palace",
                            PhoneNumber = "00962-XXX-XXXXXX",
                            State = "Amman state",
                            StreetAddress = "Jordan street"
                        },
                        new
                        {
                            HotelId = 3,
                            City = "Damascus",
                            Country = "Syria",
                            HotelName = "Four Seasons",
                            PhoneNumber = "00963-XXX-XXXXXX",
                            State = "Damascus state",
                            StreetAddress = "Damascus street"
                        });
                });

            modelBuilder.Entity("Hotel_API.Models.Room", b =>
                {
                    b.Property<int>("RoomId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Layout")
                        .HasColumnType("int");

                    b.Property<string>("RoomName")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("nvarchar(14)");

                    b.HasKey("RoomId");

                    b.ToTable("Rooms");

                    b.HasData(
                        new
                        {
                            RoomId = 1,
                            Layout = 1,
                            RoomName = "A1-1"
                        },
                        new
                        {
                            RoomId = 2,
                            Layout = 2,
                            RoomName = "A1-2"
                        },
                        new
                        {
                            RoomId = 3,
                            Layout = 0,
                            RoomName = "A1-3"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
